# Generated by Django 5.2.9 on 2025-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medius"), ("Low", "Low")],
                default="Medium",
                max_length=10,
            ),
        ),
    ]
