# Generated by Django 5.2.9 on 2025-12-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_task_due_date_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("Work", "Work"),
                    ("Study", "Study"),
                    ("Health", "Health"),
                    ("Personal", "Personal"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=250,
            ),
        ),
    ]
