# Generated by Django 5.2.9 on 2025-12-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_task_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField()),
                ("error_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
